### PR TITLE
Impl ContextMenu

### PR DESCRIPTION
**Pull request by wiiznokes**
This pull request implement #133.

I think this widget could be improved in the future by adapting menu to be used as overlay (only one tree of course not the entire bar).

The overlay appears at the place where the right click was made but apart from that, the implementation is quit naive and does not take into account the available space. But the menu have already this behaviour.

### CODE REVIEW

**Comment by genusistimelord** [comment]
Ok so in order for this to work Correctly as a right click anywhere menu you will need to remove the underlay portion from context menu.

**Comment by wiiznokes** [comment]
> Ok so in order for this to work Correctly as a right click anywhere menu

you mean if we combine menu and context menu ?

> you will need to remove the underlay portion from context menu

why ?

> Probably should make the underlay Optional actually as this might be better for those who just want to create a screen right click area

but the event is not propagated through the app. We could make a method `on_right_click` but this will be confusing I think.

And sorry but I don't understand why we need to click over other widgets ?

**Comment by genusistimelord** [comment]
well no I mean atm you are tied to the underlays position for a rigth click window. which is OK if you only want to give options of right click to certain things within a underlay. It would be nice if this could just be added and not count towards the Layout and just take right click events but this would require a special kind of change in iced. but the current method can work. we can merge this once cargo fmt is ran on the source.

**Comment by wiiznokes** [comment]
I'm not sure I have enough knowledge of Iced to understand this approach. Maybe a start of api will help me.
But I think it's already good for a start.

I finished formatting everything.
We agree that there is no auto-fix command for `cargo fmt` right?

**Comment by genusistimelord** [comment]
if you type only "cargo fmt" and nothing else it should format the entire project including anything that was missed.

**Comment by wiiznokes** [comment]
> if you type only "cargo fmt" and nothing else it should format the entire project including anything that was missed.

I guess I just lost 30 minutes :smile:

**Comment by genusistimelord** [comment]
it is a good learning Experience. You could always join the discord and ask for help on these things too.

**Pull request merged**
