### PR TITLE
add lucide font

### PR DESCRIPTION
**Pull request by Redhawk18**

### CODE REVIEW

**Comment by Redhawk18** [comment]
If you could rerun the ci

**Comment by genusistimelord** [comment]
I am not really sure if we should allow adding more fonts onto iced_aw unless they have a specific use. For example, bootstrap is actually used in the widgets. As adding these will just keep bulking down the project.

**Comment by Redhawk18** [comment]
> I am not really sure if we should allow adding more fonts onto iced_aw unless they have a specific use. For example, bootstrap is actually used in the widgets. As adding these will just keep bulking down the project.

That's true, I was requested on discord to add these. But it might not be an amazing idea.

**Comment by genusistimelord** [comment]
Would be better to make a new Font crate for Iced. One that just contains all the different fonts.

**Comment by Redhawk18** [comment]
> Would be better to make a new Font crate for Iced. One that just contains all the different fonts.

Thats prob a better idea.

**Comment by genusistimelord** [comment]
someone needs to make a iced_fonts and place any needed extra font there.

**Pull request closed without merging**
