### PR TITLE
add align option to modal

### PR DESCRIPTION
**Pull request by wiiznokes**

### CODE REVIEW

**Comment by wiiznokes** [comment]
there seems to be a problem with the use of `iced_widget::core::aligment`. It will be better to use directly `iced::alignment` but i don't think this is possible rn.

**Comment by wiiznokes** [comment]
this fix `alignment` but now, it's `Element` which have the wrong type:
```
error[E0277]: the trait bound `iced::advanced::iced_graphics::iced_core::Element<'_, AppMsg, iced_renderer::Renderer<Theme>>: std::convert::From<Modal<'_, AppMsg, _>>` is not satisfied
   --> src\app.rs:184:14
    |
184 |             .into()
    |              ^^^^ the trait `std::convert::From<Modal<'_, AppMsg, _>>` is not implemented for `iced::advanced::iced_graphics::iced_core::Element<'_, AppMsg, iced_renderer::Renderer<Theme>>`
    |
    = help: the following other types implement trait `std::convert::From<T>`:
              <iced::advanced::iced_graphics::iced_core::Element<'a, Message, Renderer> as std::convert::From<Column<'a, Message, Renderer>>>
              <iced::advanced::iced_graphics::iced_core::Element<'a, Message, Renderer> as std::convert::From<MouseArea<'a, Message, Renderer>>>
              <iced::advanced::iced_graphics::iced_core::Element<'a, Message, Renderer> as std::convert::From<Row<'a, Message, Renderer>>>
              <iced::advanced::iced_graphics::iced_core::Element<'a, Message, Renderer> as std::convert::From<iced::widget::Button<'a, Message, Renderer>>>
              <iced::advanced::iced_graphics::iced_core::Element<'a, Message, Renderer> as std::convert::From<iced::widget::Checkbox<'a, Message, Renderer>>>
              <iced::advanced::iced_graphics::iced_core::Element<'a, Message, Renderer> as std::convert::From<widgets::context_menu::widget::ContextMenu<'a, Content, Message, Renderer>>>
              <iced::advanced::iced_graphics::iced_core::Element<'a, Message, Renderer> as std::convert::From<ComboBox<'a, T, Message, Renderer>>>
              <iced::advanced::iced_graphics::iced_core::Element<'a, Message, Renderer> as std::convert::From<iced::widget::Container<'a, Message, Renderer>>>
            and 18 others
    = note: required for `Modal<'_, AppMsg, _>` to implement `Into<iced::advanced::iced_graphics::iced_core::Element<'_, AppMsg, iced_renderer::Renderer<Theme>>>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `note` (bin "note") due to previous error
```

**Comment by wiiznokes** [comment]
errors was on a personnal project. I finally found why I was getting these errors. I was using my fork of iced.
It makes me think that this is the main problem of iced_aw. We're stuck on the latest version of Iced. It would be nice to have the same system as System76 which uses a fork of Iced for their DE. Just a thought.

And seems good to me too, you can merge it :)

**Comment by genusistimelord** [comment]
they should fork it to set it to the version though really they should update to the newest iced and keep doing so. due to changed in Font rendering and other changes that should help them more.

**Review by genusistimelord — APPROVED** [review]
looks good thank you.

**Pull request merged**
