### PR TITLE
Beta

### PR DESCRIPTION
**Pull request by genusistimelord**
Added Iced Beta Via Reversion ID this way we can control when we Update the beta to the latest and only when the latest is stable without breaking changes. Solves #25 

Also includes some of the newer Clippy fixes for nightly.

### CODE REVIEW

**Comment by genusistimelord** [comment]
The new Clippy has a bunch of new checks in which one of them Messes up the Selection List as it wants 

```
where
    T: Clone + ToString + Eq,
    [T]: ToOwned<Owned = Vec<T>>,
```
    
    to become like 
    
 ```
 where
    T: Clone + ToString + Eq,
    [T]: Clone + ToString + Eq + ToOwned<Owned = Vec<T>>,
```
    
  This causes Errors with new. So will need to add Allows for it.

**Comment by genusistimelord** [comment]
I could not get the Test script to update and work right IDK why its not running the linux windows and mac tests atm. Maybe take a look when you get a chance if i have not figured it out by then. @Kaiden42

**Review by Kaiden42 — APPROVED** [review]
Looks good. I've merged the current head of the main branch in the beta branch.

Thanks for fixing the issue with the GitHub, but could you provide it as a separate PR as it would be cool to have this at the main branch too. :slightly_smiling_face: 

> The new Clippy has a bunch of new checks in which one of them Messes up the Selection List as it wants
> This causes Errors with new. So will need to add Allows for it.

As good as Clippy is, it is not perfect. Feel free to allow some lints on parts of the code where following the lint would break the code.

Is there anything else you want to change or is the PR ready to merge?

**Comment by genusistimelord** [comment]
Let me make the adjusting changes to the Selection list then it can be Merged.

**Comment by Kaiden42** [comment]
> Let me make the adjusting changes to the Selection list then it can be Merged.
I'll merge the current head of the main branch into the beta branch after I've merged this PR as I've already successfully merged your SelectionList. :slightly_smiling_face: 

> I can add the github fixes to the main via the Selection list changes or make a new PR for it if you prefer.
I would prefer a new PR for this.

> Wish I could discuss this more directly with you as it would speed up the process. Maybe a gitter channel? Telegram? Discord channel?
You can find me on Discord Kaiden42#3901

Thank you very much! :+1:

**Pull request merged**
