### PR TITLE
Added Selection List

### PR DESCRIPTION
**Pull request by genusistimelord**
A Selection list that is based on a default GUI list type. Can be modified later to add Drag and Drop events, Sorting, and other things.

### CODE REVIEW

**Comment by Kaiden42** [comment]
Looks good :+1:

However, there are some small warnings from Clippy. Would you be so kind and could please take care of it to improve your code quality a litte? :slightly_smiling_face: 

(The way clippy is currently set it is a little verbose. If you find a lint more annoying than helpful, let me notice. I'm open for a discussion. Don't mind lints that are not caused by your code and ignore the broken web as there are recently fixed by #23 and #24)

**Comment by genusistimelord** [comment]
I have fixed the Clippy issues within my source

**Comment by Kaiden42** [comment]
> I have fixed the Clippy issues within my source.

Thanks! I will now merge this :+1: 

> @Kaiden42 How are things looking on your end?

What do you mean? If you mean how it looks like with me in general, well then I'm currently neck-deep in my master's thesis. Therefore my response rate is quite low since a few weeks. I hope that's ok.

**Comment by 13r0ck** [comment]
Good luck with that thesis! :rocket:

**Comment by genusistimelord** [comment]
> 
> 
> > I have fixed the Clippy issues within my source.
> 
> Thanks! I will now merge this 👍
> 
> > @Kaiden42 How are things looking on your end?
> 
> What do you mean? If you mean how it looks like with me in general, well then I'm currently neck-deep in my master's thesis. Therefore my response rate is quite low since a few weeks. I hope that's ok.

It is ok! good luck on the thesis!

**Pull request merged**
