### PR TITLE
changed number input's bounds to an inclusive range

### PR DESCRIPTION
**Pull request by Redhawk18**

### CODE REVIEW

**Comment by Redhawk18** [comment]
I was thinking about it and theres a lot of small changes I want aswell

**Review by genusistimelord — COMMENTED** [review]
I would like you to change this to use RangeBounds So it can use any of the Range types like
..
0..
0..100
..100
0..=100

I would also like you to add an additional trait requirement. https://docs.rs/num-traits/latest/num_traits/bounds/trait.Bounded.html

This will allow use to get a min and a max for all the Generics. Which for the .. style bounds we can then set the minimal and maximum numbers to the Unbounded.

**Review by genusistimelord — DISMISSED** [review]
This looks much better. Thank you.

**Comment by Redhawk18** [comment]
@genusistimelord

**Review by genusistimelord — APPROVED** [review]
approved

**Pull request merged**
